name: Build and Push OS Image

on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Azure
      run: az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Build OS Image with Packer
      run: |
        packer init ./packer-config
        packer build -var 'client_id=${{ secrets.AZURE_CLIENT_ID }}' \
                     -var 'client_secret=${{ secrets.AZURE_CLIENT_SECRET }}' \
                     -var 'tenant_id=${{ secrets.AZURE_TENANT_ID }}' \
                     -var 'subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}' \
                     ./packer-config

    - name: Copy Image to Team Subscription
      run: |
        az image copy \
          --source-resource-group my-ci-rg \
          --source-object-name my-image \
          --target-location eastus \
          --target-resource-group team-rg \
          --target-subscription team-sub-id
